version: '3'
services:
  laravel:
    image: ghcr.io/setnemo/php:latest
    environment:
      WEBROOT: '/var/www/html/public'
      PHP_REDIS_SESSION_HOST: 'redis'
      CREATE_LARAVEL_STORAGE: '1'
      PHP_ERRORS_STDERR: '1'
    restart: always
    ports:
      - '${DOCKER_APP_PORT:-80}:80'
    volumes:
      - './app:/var/www/html'
    networks:
      - sail

networks:
  sail:
    driver: bridge